defmodule DustWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dust

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dust_key",
    signing_salt: "mGNO5sDM",
    same_site: "Lax"
  ]

  socket "/ws/sync", DustWeb.StoreSocket,
    websocket: [
      connect_info: [:peer_data],
      serializer: [
        {DustWeb.MsgpackSerializer, "3.0.0"},
        {Phoenix.Socket.V2.JSONSerializer, "~> 2.0.0"}
      ]
    ]

  socket "/ws/ui", DustWeb.UISocket, websocket: true

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dust,
    gzip: not code_reloading?,
    only: DustWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dust
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug :fetch_session
  plug Inertia.Plug
  plug DustWeb.Router
end
