defmodule DustEcto.SchemaTest do
  use ExUnit.Case, async: true

  alias DustEcto.Test.Link
  alias DustEcto.Test.FlatNote
  alias DustEcto.Test.MapLink

  describe "macro reflection" do
    test "exposes the prefix as a segment list" do
      assert Link.__dust_prefix__() == ["links"]
      assert FlatNote.__dust_prefix__() == ["notes"]
    end

    test "exposes the mode (defaults to :flat)" do
      # Link declares no :mode option → gets the default.
      assert Link.__dust_mode__() == :flat
      # FlatNote explicitly sets :flat (same as the default).
      assert FlatNote.__dust_mode__() == :flat
      # MapLink explicitly opts into :map.
      assert MapLink.__dust_mode__() == :map
    end

    test "exposes the required-fields list" do
      assert Link.__dust_required_fields__() == [:slug, :title, :url]
      assert FlatNote.__dust_required_fields__() == [:slug, :body]
    end

    test "primary key is :slug, not autogenerated" do
      assert Link.__schema__(:primary_key) == [:slug]
    end
  end

  describe "use DustEcto.Schema validation" do
    test "raises when :prefix is missing" do
      assert_raise KeyError, fn ->
        defmodule NoPrefix do
          use DustEcto.Schema, required: []
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises when :prefix is an empty list" do
      assert_raise ArgumentError, ~r/must not be empty/, fn ->
        defmodule EmptyPrefix do
          use DustEcto.Schema, prefix: []
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises with a migration hint when :prefix is a (legacy) dotted string" do
      assert_raise ArgumentError, ~r/segment list, not a string/, fn ->
        defmodule LegacyDottedPrefix do
          use DustEcto.Schema, prefix: "reading.links"
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises when :prefix segments are not non-empty strings" do
      assert_raise ArgumentError, ~r/non-empty strings/, fn ->
        defmodule BadPrefixSegment do
          use DustEcto.Schema, prefix: ["a", ""]
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises on unknown :mode" do
      assert_raise ArgumentError, ~r/:mode must be :map or :flat/, fn ->
        defmodule BadMode do
          use DustEcto.Schema, prefix: ["x"], mode: :weird
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises when :required is not a list of atoms" do
      assert_raise ArgumentError, ~r/:required must be a list of field atoms/, fn ->
        defmodule BadRequired do
          use DustEcto.Schema, prefix: ["x"], required: ["slug"]
          embedded_schema do
            field :x, :string
          end
        end
      end
    end
  end

  describe "validate_dust_slug/2" do
    test "accepts a normal slug" do
      cs = Link.changeset(%Link{}, %{slug: "hello", title: "T", url: "U"})
      assert cs.valid?
    end

    test "accepts a slug containing '.' (literal in segment-first model)" do
      # Capver 3: a slug is one path segment. Literal dots are
      # ordinary characters — `example.com` is a perfectly valid slug
      # that renders to a single-segment record path.
      cs = Link.changeset(%Link{}, %{slug: "example.com", title: "T", url: "U"})
      assert cs.valid?
    end

    test "accepts a slug containing '/' (rendered as ~1)" do
      # Literal `/` in a slug is rendered as `~1` per RFC 6901 by
      # `Dust.Protocol.Path.render/1` before hitting any wire/SQL key.
      cs = Link.changeset(%Link{}, %{slug: "a/b", title: "T", url: "U"})
      assert cs.valid?
    end

    test "rejects an empty-string slug" do
      cs = Link.changeset(%Link{}, %{slug: "", title: "T", url: "U"})
      refute cs.valid?
      # validate_required catches the empty slug first as 'required';
      # validate_dust_slug additionally adds 'cannot be empty'.
      assert is_tuple(cs.errors[:slug])
    end

    test "leaves a missing slug to validate_required (no shape error)" do
      cs = Link.changeset(%Link{}, %{title: "T", url: "U"})
      refute cs.valid?
      assert {"can't be blank", _} = cs.errors[:slug]
    end
  end
end
