defmodule DustEcto.SchemaTest do
  use ExUnit.Case, async: true

  alias DustEcto.Test.Link
  alias DustEcto.Test.FlatNote

  describe "macro reflection" do
    test "exposes the prefix" do
      assert Link.__dust_prefix__() == "links"
      assert FlatNote.__dust_prefix__() == "notes"
    end

    test "exposes the mode (defaults to :map)" do
      assert Link.__dust_mode__() == :map
      assert FlatNote.__dust_mode__() == :flat
    end

    test "exposes the required-fields list" do
      assert Link.__dust_required_fields__() == [:slug, :title, :url]
      assert FlatNote.__dust_required_fields__() == [:slug, :body]
    end

    test "primary key is :slug, not autogenerated" do
      assert Link.__schema__(:primary_key) == [:slug]
    end
  end

  describe "use DustEcto.Schema validation" do
    test "raises when :prefix is missing" do
      assert_raise KeyError, fn ->
        defmodule NoPrefix do
          use DustEcto.Schema, required: []
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises when :prefix is empty" do
      assert_raise ArgumentError, ~r/non-empty :prefix/, fn ->
        defmodule EmptyPrefix do
          use DustEcto.Schema, prefix: ""
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises on unknown :mode" do
      assert_raise ArgumentError, ~r/:mode must be :map or :flat/, fn ->
        defmodule BadMode do
          use DustEcto.Schema, prefix: "x", mode: :weird
          embedded_schema do
            field :x, :string
          end
        end
      end
    end

    test "raises when :required is not a list of atoms" do
      assert_raise ArgumentError, ~r/:required must be a list of field atoms/, fn ->
        defmodule BadRequired do
          use DustEcto.Schema, prefix: "x", required: ["slug"]
          embedded_schema do
            field :x, :string
          end
        end
      end
    end
  end

  describe "validate_dust_slug/2" do
    test "accepts a normal slug" do
      cs = Link.changeset(%Link{}, %{slug: "hello", title: "T", url: "U"})
      assert cs.valid?
    end

    test "rejects a slug containing '.'" do
      cs = Link.changeset(%Link{}, %{slug: "a.b", title: "T", url: "U"})
      refute cs.valid?
      assert {"cannot contain '.'" <> _, _} = cs.errors[:slug]
    end

    test "rejects a slug containing '/'" do
      cs = Link.changeset(%Link{}, %{slug: "a/b", title: "T", url: "U"})
      refute cs.valid?
      assert {"cannot contain '/'" <> _, _} = cs.errors[:slug]
    end

    test "rejects an empty-string slug" do
      cs = Link.changeset(%Link{}, %{slug: "", title: "T", url: "U"})
      refute cs.valid?
      # validate_required catches the empty slug first as 'required';
      # validate_dust_slug additionally adds 'cannot be empty'.
      assert is_tuple(cs.errors[:slug])
    end

    test "leaves a missing slug to validate_required (no shape error)" do
      cs = Link.changeset(%Link{}, %{title: "T", url: "U"})
      refute cs.valid?
      assert {"can't be blank", _} = cs.errors[:slug]
    end
  end
end
