require "./dust/config"
require "./dust/output"
require "./dust/glob"
require "./dust/cache/sqlite"
require "./dust/client/channel"
require "./dust/client/connection"
require "./dust/commands/auth"
require "./dust/commands/init"
require "./dust/commands/store"
require "./dust/commands/data"
require "./dust/commands/types"
require "./dust/commands/files"
require "./dust/commands/watch"
require "./dust/commands/log"
require "./dust/commands/export"
require "./dust/commands/import"
require "./dust/commands/clone"
require "./dust/commands/diff"
require "./dust/commands/token"
require "./dust/commands/webhook"
require "./dust/cli"

Dust::CLI.run(ARGV)
